### ISSUE TITLE
Commit Count set to 3 on 3 node cluster.

### ISSUE THREAD

**Issue by pgermishuys** [nissbran/eventstore-cluster-docker-compose#1]
In the local 3 [node cluster configuration](https://github.com/nissbran/eventstore-cluster-docker-compose/blob/master/local-3-node-cluster/common-variables.env#L2) the commit count is set to 3 which means that once a single node in the 3 node cluster is down, no writes will be able to completed successfully.

**Comment by nissbran** [comment]
Thanks for the information. I have changed the commit count to 2.

**Comment by nissbran** [comment]
I also updated to 4.0 :)

**Comment by pgermishuys** [comment]
You shouldn't need to set the commit count explicitly. The calculated values should be fine. .e.g `node count / 2 + 1`

**Comment by nissbran** [comment]
Ok, so the eventstore has an internal calculation of commit count? If it has, i might be a good idea to have that information in the documentation for the server settings (in [http://docs.geteventstore.com/server/4.0.0/command-line-arguments/])

**Comment by pgermishuys** [comment]
Yes sir,
For example this is the method that calculates the commit/prepare count.
https://github.com/EventStore/EventStore/blob/release-v4.0.2/src/EventStore.Core/VNodeBuilder.cs#L218

Which is called here if the cluster size is > 1.
https://github.com/EventStore/EventStore/blob/56c5680f51325cf0e99846da72ae313402c63c2d/src/EventStore.ClusterNode/Program.cs#L165
